name: paymentez
description: Paymentez SDK for Ecuador.
version: 0.5.0
author: Jean Roldan at Paymentez
homepage: https://www.paymentez.com.ec/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.2
  crypto: 2.1.5
  dart_ipify: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:

flutter:
