name: paymentez_sdk
description: Paymentez SDK for Ecuador.
version: 0.5.2
homepage: https://www.paymentez.com.ec/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  http: ^1.1.0

dev_dependencies:
  mocktail: 1.0.1
  test: ^1.19.2
  very_good_analysis: 5.1.0
